### ISSUE TITLE
c call go dll And c register callback function go callbakc 

### ISSUE THREAD

**Issue by eurake** [zj360202/TestCpp#1]
你好！
当前遇到这样子的一个需求。 
 用golang 编写dll 由c/c++ 调用， c/c++ 调用golang的导出的函数时并注册回调函数，golang dll 进入运行后，当有数据时主动回调注册函数， 把数据通回调函数给c/c++，能否在这方面指点下

**Comment by zj360202** [comment]
我没有写过c/c++调用golang dll的情况，抱歉
